# Generated by Django 2.2.4 on 2019-09-20 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sweetrelish_enabled', models.BooleanField(default=False)),
                ('sweetrelish_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiAccountMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_members', to='pronym_api.ApiAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_api_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenWhitelistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('api_account_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_token_whitelist_entries', to='pronym_api.ApiAccountMember')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('endpoint_name', models.CharField(max_length=255)),
                ('source_ip', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('is_authenticated', models.BooleanField()),
                ('request_method', models.CharField(max_length=255)),
                ('request_headers', models.TextField()),
                ('request_payload', models.TextField()),
                ('response_payload', models.TextField()),
                ('status_code', models.PositiveIntegerField()),
                ('authenticated_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pronym_api.ApiAccountMember')),
            ],
        ),
    ]
