# Generated by Django 2.2.4 on 2019-09-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiaccount',
            name='is_sweetrelish_enabled',
        ),
        migrations.RemoveField(
            model_name='apiaccount',
            name='sweetrelish_email',
        ),
    ]
