# Generated by Django 2.2.4 on 2019-09-21 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0003_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='datetime_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
