# Generated by Django 2.2.4 on 2019-09-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0004_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenwhitelistentry',
            name='token_entropy',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
