# Generated by Django 2.2.4 on 2019-09-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0005_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenwhitelistentry',
            name='token_entropy',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
