# Generated by Django 2.2.4 on 2019-09-24 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0006_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccountmember',
            name='api_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pronym_api.ApiAccount'),
        ),
        migrations.AlterField(
            model_name='apiaccountmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='authenticated_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='pronym_api.ApiAccountMember'),
        ),
        migrations.AlterField(
            model_name='tokenwhitelistentry',
            name='api_account_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_whitelist_entries', to='pronym_api.ApiAccountMember'),
        ),
    ]
