# Generated by Django 2.2.4 on 2020-01-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0007_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccount',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
