# Generated by Django 2.2.4 on 2020-05-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0008_auto'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apiaccountmember',
            index=models.Index(fields=['api_account'], name='pronym_api__api_acc_05e9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='apiaccountmember',
            index=models.Index(fields=['user'], name='pronym_api__user_id_d87337_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['datetime_added'], name='pronym_api__datetim_5efe77_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['authenticated_profile'], name='pronym_api__authent_300995_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenwhitelistentry',
            index=models.Index(fields=['token_entropy'], name='pronym_api__token_e_df852c_idx'),
        ),
    ]
