# Generated by Django 3.0.5 on 2020-06-01 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0009_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='api_account',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='pronym_api.ApiAccount'),
        ),
        migrations.AlterField(
            model_name='apiaccountmember',
            name='api_account',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='pronym_api.ApiAccount'),
        ),
    ]
