# Generated by Django 3.0.8 on 2020-10-18 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0009_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='api_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='pronym_api.ApiAccount'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='authenticated_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='pronym_api.ApiAccountMember'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['api_account'], name='pronym_api__api_acc_ecd3a6_idx'),
        ),
    ]
