# Generated by Django 2.2.4 on 2020-01-11 19:57

from django.db import migrations
from django.db.models import F


def update_api_account(apps, schema_editor):
    LogEntry = apps.get_model('pronym_api', 'LogEntry')

    LogEntry\
        .objects\
        .select_related('authenticated_profile')\
        .all()\
        .update(api_account=F('authenticated_profile__api_account'))


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0010_auto'),
    ]

    operations = [
        migrations.RunPython(update_api_account)
    ]
