# Generated by Django 3.0.8 on 2020-10-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0011_migrate_api_account'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='logentry',
            name='pronym_api__datetim_5efe77_idx',
        ),
        migrations.RemoveIndex(
            model_name='logentry',
            name='pronym_api__authent_300995_idx',
        ),
        migrations.RemoveIndex(
            model_name='logentry',
            name='pronym_api__api_acc_ecd3a6_idx',
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['api_account', 'datetime_added'], name='pronym_api__api_acc_b4dc4b_idx'),
        ),
    ]
