# Generated by Django 3.0.8 on 2020-10-18 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0012_change_indices'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='logentry',
            name='pronym_api__api_acc_b4dc4b_idx',
        ),
        migrations.AlterField(
            model_name='logentry',
            name='datetime_added',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
