# Generated by Django 3.0.8 on 2020-11-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronym_api', '0013_change_indices_again'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='apiaccount',
            name='permissions',
            field=models.ManyToManyField(related_name='api_accounts', to='pronym_api.ApiPermission'),
        ),
        migrations.AddField(
            model_name='apiaccountmember',
            name='permissions',
            field=models.ManyToManyField(related_name='api_account_members', to='pronym_api.ApiPermission'),
        ),
    ]
